/* tslint:disable */
/* eslint-disable */
/**
 * Swagger Petstore - OpenAPI 3.0
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.11
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError } from './base';

/**
 * 
 * @export
 * @interface Data
 */
export interface Data {
    /**
     * 
     * @type {number}
     * @memberof Data
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof Data
     */
    'username'?: string;
    /**
     * 
     * @type {string}
     * @memberof Data
     */
    'firstName'?: string;
    /**
     * 
     * @type {string}
     * @memberof Data
     */
    'lastName'?: string;
    /**
     * 
     * @type {string}
     * @memberof Data
     */
    'email'?: string;
    /**
     * 
     * @type {string}
     * @memberof Data
     */
    'password'?: string;
    /**
     * 
     * @type {string}
     * @memberof Data
     */
    'phone'?: string;
    /**
     * User Status
     * @type {number}
     * @memberof Data
     */
    'userStatus'?: number;
}

/**
 * SampleApiApi - axios parameter creator
 * @export
 */
export const SampleApiApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * sampleApi
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        dataGet: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/data`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * SampleApiApi - functional programming interface
 * @export
 */
export const SampleApiApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = SampleApiApiAxiosParamCreator(configuration)
    return {
        /**
         * sampleApi
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async dataGet(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Data>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.dataGet(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * SampleApiApi - factory interface
 * @export
 */
export const SampleApiApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = SampleApiApiFp(configuration)
    return {
        /**
         * sampleApi
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        dataGet(options?: any): AxiosPromise<Data> {
            return localVarFp.dataGet(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * SampleApiApi - object-oriented interface
 * @export
 * @class SampleApiApi
 * @extends {BaseAPI}
 */
export class SampleApiApi extends BaseAPI {
    /**
     * sampleApi
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SampleApiApi
     */
    public dataGet(options?: AxiosRequestConfig) {
        return SampleApiApiFp(this.configuration).dataGet(options).then((request) => request(this.axios, this.basePath));
    }
}


